import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { register } from "swiper/element";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

register();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sollyverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-50 dark:bg-slate-800 text-gray-600 dark:text-gray-100`}
      >
        <section className="app">
          <Nav />
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
